# Generated by Django 4.2.5 on 2023-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0003_finance_goals_operations_sales_metrics_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='Month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='goals',
            name='Overall',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
