# Generated by Django 4.2.5 on 2023-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0004_alter_goals_month_alter_goals_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='Month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='networth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
