# Generated by Django 4.2.5 on 2023-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0005_alter_goals_month_alter_goals_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('networth', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goals2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(blank=True, max_length=20, null=True)),
                ('networth', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='goals',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='Year',
        ),
    ]
