# Generated by Django 4.2.5 on 2023-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0007_goals_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeCommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'get_latest_by': 'milestone'},
        ),
        migrations.RemoveField(
            model_name='operations',
            name='Team',
        ),
        migrations.AddField(
            model_name='finance',
            name='asset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='liab',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='liquid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='avail',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='inventory1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='inventory2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='supply',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='salefigures',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
