# Generated by Django 4.2.5 on 2023-09-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0009_rename_inventory1_operations_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='cash',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='order',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
