# Generated by Django 4.2.5 on 2023-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0010_finance_cash_finance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
