# Generated by Django 3.2.4 on 2024-05-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0013_auto_20240519_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='Client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='finance',
            name='cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='order',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
