# Generated by Django 5.0.7 on 2024-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0014_auto_20240519_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_transactions', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
