# Generated by Django 5.0.7 on 2024-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0015_salesfigure_delete_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('machine_utilization_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('labor_efficiency_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('stock_turnover_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('leads_generated', models.IntegerField()),
                ('leads_converted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('units_produced', models.IntegerField()),
                ('production_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defect_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_lead_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.DeleteModel(
            name='Goals1',
        ),
        migrations.DeleteModel(
            name='Goals2',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
